### ISSUE TITLE
simple_server.js not recognizing any commands

### ISSUE THREAD

**Issue by caseytrussell** [spark/local-communication-example#2]
Hello, I am able to connect to the server with no issue and get feedback from the client and server that the connection is established. However, when I send 0h, 7l, x, etc., the server jumps here: 
     
      console.log("Commands: 0h  Set pin D0 high");
      console.log("                    7l  Set pin D7 low");
      console.log("                    Any pin 0-7 may be set high or low");
      console.log("                    x   Exit");

I have tried in node.js, cmd, and gitbash, and all have same result.
Do you think I am doing anything wrong? Is there any syntax I may be missing?
I could be wrong, but I have a feeling the issue is somewhere in here:

    process.stdin.on('data', function(d) {
    d = d.toString('utf8', 0, d.length - 1);
    if (/^[0-7][lh]$/i.test(d)) {
    socket.write(d.toLowerCase()); }

I hate to be the only one with an issue, but I'm stumped.
Any help would be appreciated.
Thank you

**Comment by dmiddlecamp** [comment]
Hmm, so that last case indicates the regex test failed.  I wonder, are you typing spaces via stdin?

breaking those lines down yields:

```
// when someone types something on the keyboard
process.stdin.on('data', function(d) {

// convert it into a string, utf8 please
d = d.toString('utf8', 0, d.length - 1);

// is the character an ascii number between 0-7, or the letters "l" or "h" ?
if (/^[0-7][lh]$/i.test(d)) {

// if so, then write it to the socket
socket.write(d.toLowerCase()); }

// else...
```

**Comment by dmiddlecamp** [comment]
Something nice about node is the interactive repl, open a terminal and type node:

```
$ node
> /^[0-7][lh]$/i.test()
false
> /^[0-7][lh]$/i.test(" ")
false
> /^[0-7][lh]$/i.test("0")
false
> /^[0-7][lh]$/i.test('0')
false
> /^[0-7][lh]$/i.test(0')
... 
> /^[0-7][lh]$/i.test("0h")
true
> 
(^C again to quit)
> 

```

**Comment by caseytrussell** [comment]
Sorry, I am not sure what you are asking me to do? Could you give me more specific instructions?

**Comment by caseytrussell** [comment]
I am not typing any spaces to answer your previous question

**Comment by caseytrussell** [comment]
Not sure if this is what you were asking for...

Your environment has been set up for using Node.js 5.6.0 (x64) and npm.

C:\Users\Casey>node
> $ node
$ node
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:225:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
> > /^[0-7][lh]$/i.test()
... false
... > /^[0-7][lh]$/i.test(" ")
... false
... > /^[0-7][lh]$/i.test("0")
... false
... > /^[0-7][lh]$/i.test('0')
... false
... > /^[0-7][lh]$/i.test(0')
SyntaxError: Unexpected token >
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:225:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
> ...
Invalid REPL keyword
> > /^[0-7][lh]$/i.test("0h")
... true
... >
... (^C again to quit)
... >

**Comment by dmiddlecamp** [comment]
Hi @caseytrussell ,

  Sorry, I was demonstrating how the regex works by displaying the output of node on my box.  I suspect the stdin data event is being triggered for every keypress, instead of when the user hits enter, which was the old behavior  (I think).

```
//old code:
  process.stdin.on('data', function(d) {
    d = d.toString('utf8', 0, d.length - 1);

//new code:
    var letters = [];
    process.stdin.on('data', function(d) {
    	d = d.toString('utf8', 0, d.length - 1);
    	letters.push(d);

    	if (d == "\n") {
    		d = letters.join("").trim();
    	}
    	else {
    		return;
    	}
    	//... splice into conditional from old code

```

I'm not able to fully test this and patch this for both newer / older versions of node at the moment, but here's a demonstration of a code change that will accumulate characters into an array until a newline is heard, and then continue on.  I'll revisit this and fix it properly for updated node versions when I get a chance!  Also you could try reverting to an older version of node in the meantime if you wanted to try that.  (0.10, or 0.12 I suspect).

Thanks!
David

**Comment by caseytrussell** [comment]
Cool. I give that a shot. I'll let you know if it works

**Comment by mohitagnihotri** [comment]
I'm also facing same problem. simple_server.js not recognizing any commands. 
![issue](https://cloud.githubusercontent.com/assets/6417665/13871577/1549f2d4-ed0a-11e5-94b7-18c97bb5ad28.png)

If @caseytrussell or anyone has working code/solution then please update here.
